import { db, categoriesTable, businessesTable, reviewsTable, businessUsersTable, productsTable } from "@workspace/db";
import { count } from "drizzle-orm";
import { logger } from "./logger";
import bcrypt from "bcryptjs";

const DEFAULT_PASSWORD = "Hub@2026";

export async function runStartupSeed() {
  try {
    const [{ value: catCount }] = await db.select({ value: count() }).from(categoriesTable);

    if (Number(catCount) > 0) {
      logger.info({ categories: catCount }, "Database already seeded, skipping");
      return;
    }

    logger.info("Database is empty — running startup seed...");

    const categories = await db
      .insert(categoriesTable)
      .values([
        { slug: "restaurantes", name: "Restaurantes", icon: "Utensils", color: "#E53E3E", photoUrl: null },
        { slug: "saloes", name: "Salões de Beleza", icon: "Scissors", color: "#D53F8C", photoUrl: null },
        { slug: "academias", name: "Academias", icon: "Dumbbell", color: "#3182CE", photoUrl: null },
        { slug: "mercados", name: "Mercados", icon: "ShoppingCart", color: "#38A169", photoUrl: null },
        { slug: "cafeterias", name: "Cafeterias", icon: "Coffee", color: "#D69E2E", photoUrl: null },
        { slug: "pet-shops", name: "Pet Shops", icon: "Dog", color: "#805AD5", photoUrl: null },
        { slug: "farmácias", name: "Farmácias", icon: "Pill", color: "#319795", photoUrl: null },
        { slug: "servicos", name: "Serviços", icon: "Wrench", color: "#DD6B20", photoUrl: null },
        { slug: "padarias", name: "Padarias", icon: "Cake", color: "#ECC94B", photoUrl: null },
        { slug: "saude", name: "Saúde", icon: "Heart", color: "#FC8181", photoUrl: null },
      ])
      .returning();

    logger.info({ count: categories.length }, "Categories seeded");

    const businesses = await db
      .insert(businessesTable)
      .values([
        {
          name: "Restaurante Sabor do Sul",
          categorySlug: "restaurantes",
          region: "Centro",
          description: "Gastronomia gaúcha autêntica com rodízio de carnes e buffet caprichado. Ambiente familiar e aconchegante no coração de Londrina.",
          address: "Rua Sergipe, 240 - Centro, Londrina",
          phone: "(43) 3322-1100",
          whatsapp: "5543991112233",
          rating: 4.7,
          reviewsCount: 134,
          planType: "premium",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
          hours: "Seg-Dom: 11h30–15h | 19h–23h",
          zone: "centro",
          cnpj: "12.345.678/0001-01",
          ownerName: "Ricardo Gonçalves",
          ownerEmail: "contato@sabordosul.com.br",
          ownerPhone: "(43) 99911-2233",
          cep: "86010-350",
          street: "Rua Sergipe",
          number: "240",
          neighborhood: "Centro",
          lat: "-23.3045",
          lng: "-51.1696",
          instagram: "@sabordosullondrina",
          paymentMethods: ["Dinheiro", "PIX", "Cartão de crédito", "Cartão de débito", "Vale refeição"],
          tags: ["churrasco", "buffet", "rodízio", "gaúcho", "almoço"],
        },
        {
          name: "Churrascaria Pantanal",
          categorySlug: "restaurantes",
          region: "Zona Sul",
          description: "Tradição de 20 anos em churrasco de qualidade. Cortes nobres, espeto corrido e ambiente sofisticado na Gleba Palhano.",
          address: "Av. Ayrton Senna, 1840 - Gleba Palhano, Londrina",
          phone: "(43) 3344-5566",
          whatsapp: "5543998887766",
          rating: 4.8,
          reviewsCount: 289,
          planType: "premium",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
          hours: "Seg-Dom: 12h–15h | 19h–23h30",
          zone: "sul",
          cnpj: "23.456.789/0001-02",
          ownerName: "Marcos Ferreira",
          ownerEmail: "contato@churrascariapantanal.com.br",
          ownerPhone: "(43) 99888-7766",
          cep: "86050-170",
          street: "Avenida Ayrton Senna da Silva",
          number: "1840",
          neighborhood: "Gleba Palhano",
          lat: "-23.3280",
          lng: "-51.1870",
          instagram: "@churrascariapantanal",
          website: "https://churrascariapantanal.com.br",
          paymentMethods: ["Dinheiro", "PIX", "Cartão de crédito", "Cartão de débito"],
          tags: ["churrasco", "espeto corrido", "cortes nobres", "premium"],
        },
        {
          name: "Cantina da Nona",
          categorySlug: "restaurantes",
          region: "Zona Norte",
          description: "Massas artesanais e pizzas napolitanas feitas com ingredientes frescos. Receitas da família desde 1985.",
          address: "Rua Marechal Cândido Rondon, 820 - Conjunto Cafezal, Londrina",
          phone: "(43) 3355-7788",
          whatsapp: "5543992221133",
          rating: 4.5,
          reviewsCount: 97,
          planType: "destaque",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1498579150354-977475b7ea0b?w=800",
          hours: "Ter-Dom: 18h–23h",
          zone: "norte",
          cnpj: "34.567.890/0001-03",
          ownerName: "Maria Antonella Bianchi",
          ownerEmail: "contato@cantinadanona.com.br",
          ownerPhone: "(43) 99222-1133",
          cep: "86027-610",
          street: "Rua Marechal Cândido Rondon",
          number: "820",
          neighborhood: "Conjunto Cafezal",
          lat: "-23.2780",
          lng: "-51.1560",
          instagram: "@cantinadanona",
          paymentMethods: ["Dinheiro", "PIX", "Cartão de crédito", "Vale refeição"],
          tags: ["massas", "pizza", "italiano", "delivery"],
        },
        {
          name: "Salão Studio Glamour",
          categorySlug: "saloes",
          region: "Zona Sul",
          description: "Especialistas em coloração, cortes modernos, tratamentos capilares e nail art. Profissionais certificados e atendimento premium.",
          address: "Av. Madre Leônia Milito, 500 - Gleba Palhano, Londrina",
          phone: "(43) 3366-9900",
          whatsapp: "5543997776655",
          rating: 4.9,
          reviewsCount: 201,
          planType: "premium",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800",
          hours: "Seg-Sáb: 9h–20h",
          zone: "sul",
          cnpj: "45.678.901/0001-04",
          ownerName: "Juliana Martins",
          ownerEmail: "contato@studioglamour.com.br",
          ownerPhone: "(43) 99777-6655",
          cep: "86050-271",
          street: "Avenida Madre Leônia Milito",
          number: "500",
          neighborhood: "Gleba Palhano",
          lat: "-23.3310",
          lng: "-51.1910",
          instagram: "@studioglamourlondrina",
          website: "https://studioglamour.com.br",
          paymentMethods: ["Dinheiro", "PIX", "Cartão de crédito", "Cartão de débito"],
          tags: ["cabelo", "coloração", "nail art", "tratamento capilar"],
        },
        {
          name: "Bela Imagem Cabeleireiro",
          categorySlug: "saloes",
          region: "Centro",
          description: "Cortes masculinos e femininos, escova progressiva e hidratação capilar. Localizado no centro de Londrina com fácil estacionamento.",
          address: "Rua Minas Gerais, 156 - Centro, Londrina",
          phone: "(43) 3311-4433",
          whatsapp: "5543993334455",
          rating: 4.3,
          reviewsCount: 88,
          planType: "destaque",
          verified: false,
          photoUrl: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800",
          hours: "Seg-Sex: 9h–19h | Sáb: 9h–17h",
          zone: "centro",
          cnpj: "56.789.012/0001-05",
          ownerName: "Anderson Pereira",
          ownerEmail: "contato@belaimagem.com.br",
          ownerPhone: "(43) 99333-4455",
          cep: "86020-060",
          street: "Rua Minas Gerais",
          number: "156",
          neighborhood: "Centro",
          lat: "-23.3070",
          lng: "-51.1630",
          instagram: "@belaimagemlondrina",
          paymentMethods: ["Dinheiro", "PIX", "Cartão de débito"],
          tags: ["corte masculino", "escova progressiva", "hidratação"],
        },
        {
          name: "Academia Força Total",
          categorySlug: "academias",
          region: "Zona Sul",
          description: "Musculação, crossfit, aulas coletivas e personal trainer. Equipamentos de última geração e instrutores qualificados.",
          address: "Rua Hugo Cabral, 390 - Vila Casoni, Londrina",
          phone: "(43) 3377-2200",
          whatsapp: "5543996665544",
          rating: 4.6,
          reviewsCount: 145,
          planType: "premium",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800",
          hours: "Seg-Sex: 5h–23h | Sáb: 7h–18h | Dom: 8h–14h",
          zone: "sul",
          cnpj: "67.890.123/0001-06",
          ownerName: "Thiago Rodrigues",
          ownerEmail: "contato@forcatotal.com.br",
          ownerPhone: "(43) 99666-5544",
          cep: "86015-480",
          street: "Rua Hugo Cabral",
          number: "390",
          neighborhood: "Vila Casoni",
          lat: "-23.3120",
          lng: "-51.1550",
          instagram: "@forcatotallondrina",
          website: "https://forcatotal.com.br",
          paymentMethods: ["PIX", "Cartão de crédito", "Cartão de débito"],
          tags: ["musculação", "crossfit", "personal trainer", "aulas coletivas"],
        },
        {
          name: "FitLife Academia",
          categorySlug: "academias",
          region: "Zona Leste",
          description: "Academia moderna com spinning, pilates, zumba e musculação. Planos acessíveis para toda a família no Jardim Québec.",
          address: "Rua Prefeito Hugo Cabral, 1120 - Jardim Québec, Londrina",
          phone: "(43) 3388-1144",
          whatsapp: "5543991234567",
          rating: 4.4,
          reviewsCount: 76,
          planType: "destaque",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800",
          hours: "Seg-Sex: 6h–22h | Sáb: 7h–17h | Dom: 8h–13h",
          zone: "leste",
          cnpj: "78.901.234/0001-07",
          ownerName: "Camila de Souza",
          ownerEmail: "contato@fitlife.com.br",
          ownerPhone: "(43) 99123-4567",
          cep: "86065-390",
          street: "Rua Prefeito Hugo Cabral",
          number: "1120",
          neighborhood: "Jardim Québec",
          lat: "-23.3200",
          lng: "-51.1420",
          instagram: "@fitlifelondrina",
          paymentMethods: ["PIX", "Cartão de crédito", "Cartão de débito"],
          tags: ["spinning", "pilates", "zumba", "musculação"],
        },
        {
          name: "Supermercado Bom Preço",
          categorySlug: "mercados",
          region: "Zona Norte",
          description: "Supermercado completo com açougue próprio, padaria, hortifruti e seção de vinhos. Entrega em toda Londrina.",
          address: "Av. Saul Elkind, 2300 - Conjunto Parigot de Souza, Londrina",
          phone: "(43) 3399-5500",
          whatsapp: "5543995556677",
          rating: 4.2,
          reviewsCount: 312,
          planType: "premium",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1534723328310-e82dad3ee43f?w=800",
          hours: "Seg-Sáb: 7h–22h | Dom: 8h–20h",
          zone: "norte",
          cnpj: "89.012.345/0001-08",
          ownerName: "José Carlos Ribeiro",
          ownerEmail: "contato@bompreco.com.br",
          ownerPhone: "(43) 99555-6677",
          cep: "86082-000",
          street: "Avenida Saul Elkind",
          number: "2300",
          neighborhood: "Conjunto Parigot de Souza",
          lat: "-23.2610",
          lng: "-51.1380",
          instagram: "@bomprecolondrina",
          paymentMethods: ["Dinheiro", "PIX", "Cartão de crédito", "Cartão de débito", "Vale refeição"],
          tags: ["supermercado", "açougue", "hortifruti", "delivery", "vinhos"],
        },
        {
          name: "Mini Mercado Família",
          categorySlug: "mercados",
          region: "Zona Leste",
          description: "Mercado de bairro com produtos frescos, padaria artesanal e atendimento personalizado. Tradição de 15 anos no Jardim Québec.",
          address: "Rua Ângelo Moreira da Fonseca, 88 - Jardim Québec, Londrina",
          phone: "(43) 3300-7766",
          whatsapp: "5543994443322",
          rating: 4.1,
          reviewsCount: 52,
          planType: "free",
          verified: false,
          photoUrl: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800",
          hours: "Seg-Sáb: 7h–21h | Dom: 8h–18h",
          zone: "leste",
          cnpj: "90.123.456/0001-09",
          ownerName: "Fátima Almeida",
          ownerEmail: "contato@minimercadofamilia.com.br",
          ownerPhone: "(43) 99444-3322",
          cep: "86065-320",
          street: "Rua Ângelo Moreira da Fonseca",
          number: "88",
          neighborhood: "Jardim Québec",
          lat: "-23.3190",
          lng: "-51.1400",
          instagram: "@minimercadofamilia",
          paymentMethods: ["Dinheiro", "PIX"],
          tags: ["mercado", "padaria", "bairro"],
        },
        {
          name: "Café Aroma & Arte",
          categorySlug: "cafeterias",
          region: "Centro",
          description: "Cafeteria especialidade com grãos selecionados de origem única, métodos alternativos e ambiente acolhedor para trabalho e estudo.",
          address: "Rua Belo Horizonte, 73 - Centro, Londrina",
          phone: "(43) 3322-8800",
          whatsapp: "5543999887766",
          rating: 4.8,
          reviewsCount: 178,
          planType: "premium",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800",
          hours: "Seg-Sex: 7h–20h | Sáb: 8h–19h | Dom: 9h–17h",
          zone: "centro",
          cnpj: "01.234.567/0001-10",
          ownerName: "Luciana Campos",
          ownerEmail: "contato@cafearte.com.br",
          ownerPhone: "(43) 99988-7766",
          cep: "86020-060",
          street: "Rua Belo Horizonte",
          number: "73",
          neighborhood: "Centro",
          lat: "-23.3055",
          lng: "-51.1645",
          instagram: "@cafeartelondrina",
          website: "https://cafearte.com.br",
          paymentMethods: ["Dinheiro", "PIX", "Cartão de crédito", "Cartão de débito"],
          tags: ["café especial", "coworking", "brunch", "métodos alternativos"],
        },
        {
          name: "Grão Especial Café",
          categorySlug: "cafeterias",
          region: "Zona Sul",
          description: "Café da manhã completo, almoço executivo e cafés especiais. O point favorito da Gleba Palhano para reuniões.",
          address: "Av. Ayrton Senna, 560 - Gleba Palhano, Londrina",
          phone: "(43) 3344-9988",
          whatsapp: "5543992233445",
          rating: 4.6,
          reviewsCount: 93,
          planType: "destaque",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
          hours: "Seg-Sex: 7h–19h | Sáb-Dom: 8h–18h",
          zone: "sul",
          cnpj: "12.345.098/0001-11",
          ownerName: "Eduardo Nakamura",
          ownerEmail: "contato@graoespecial.com.br",
          ownerPhone: "(43) 99223-3445",
          cep: "86050-170",
          street: "Avenida Ayrton Senna da Silva",
          number: "560",
          neighborhood: "Gleba Palhano",
          lat: "-23.3270",
          lng: "-51.1850",
          instagram: "@graoespeciallondrina",
          paymentMethods: ["Dinheiro", "PIX", "Cartão de crédito"],
          tags: ["café", "brunch", "almoço executivo", "reunião"],
        },
        {
          name: "Pet Shop Patinhas Felizes",
          categorySlug: "pet-shops",
          region: "Zona Sul",
          description: "Banho e tosa, veterinária, produtos premium para pets e acessórios. Cuidando do seu melhor amigo com amor e profissionalismo.",
          address: "Rua Monteiro Lobato, 450 - Vila Casoni, Londrina",
          phone: "(43) 3355-6677",
          whatsapp: "5543998001122",
          rating: 4.7,
          reviewsCount: 116,
          planType: "destaque",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800",
          hours: "Seg-Sáb: 8h–19h",
          zone: "sul",
          cnpj: "23.456.109/0001-12",
          ownerName: "Renata Oliveira",
          ownerEmail: "contato@patinhasfelizes.com.br",
          ownerPhone: "(43) 99800-1122",
          cep: "86015-520",
          street: "Rua Monteiro Lobato",
          number: "450",
          neighborhood: "Vila Casoni",
          lat: "-23.3100",
          lng: "-51.1510",
          instagram: "@patinhasfelizeslondrina",
          paymentMethods: ["Dinheiro", "PIX", "Cartão de crédito", "Cartão de débito"],
          tags: ["banho e tosa", "pet shop", "acessórios pet", "ração"],
        },
        {
          name: "VetCare Clínica Veterinária",
          categorySlug: "pet-shops",
          region: "Centro",
          description: "Clínica veterinária completa com consultas, cirurgias, vacinação, exames e internação. Plantão 24h para emergências.",
          address: "Rua Tocantins, 310 - Centro, Londrina",
          phone: "(43) 3311-5500",
          whatsapp: "5543997770011",
          rating: 4.9,
          reviewsCount: 204,
          planType: "premium",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800",
          hours: "Seg-Sex: 8h–20h | Sáb: 8h–17h | Plantão 24h",
          zone: "centro",
          cnpj: "34.567.210/0001-13",
          ownerName: "Dr. Felipe Santos",
          ownerEmail: "contato@vetcare.com.br",
          ownerPhone: "(43) 99777-0011",
          cep: "86010-210",
          street: "Rua Tocantins",
          number: "310",
          neighborhood: "Centro",
          lat: "-23.3030",
          lng: "-51.1670",
          instagram: "@vetcarelondrina",
          website: "https://vetcarelondrina.com.br",
          paymentMethods: ["Dinheiro", "PIX", "Cartão de crédito", "Cartão de débito"],
          tags: ["veterinário", "plantão 24h", "cirurgia animal", "vacinação"],
        },
        {
          name: "Farmácia Saúde Londrina",
          categorySlug: "farmácias",
          region: "Centro",
          description: "Farmácia completa com manipulação própria, dermocosméticos, vitaminas e entrega rápida. Farmacêutico sempre disponível.",
          address: "Rua Paranaguá, 120 - Centro, Londrina",
          phone: "(43) 3322-3300",
          whatsapp: "5543996660099",
          rating: 4.4,
          reviewsCount: 67,
          planType: "destaque",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=800",
          hours: "Seg-Sáb: 7h–22h | Dom: 8h–20h",
          zone: "centro",
          cnpj: "45.678.321/0001-14",
          ownerName: "Dra. Patrícia Mendes",
          ownerEmail: "contato@farmaciasaude.com.br",
          ownerPhone: "(43) 99666-0099",
          cep: "86020-030",
          street: "Rua Paranaguá",
          number: "120",
          neighborhood: "Centro",
          lat: "-23.3065",
          lng: "-51.1620",
          instagram: "@farmaciasaudelondrina",
          paymentMethods: ["Dinheiro", "PIX", "Cartão de crédito", "Cartão de débito"],
          tags: ["farmácia", "manipulação", "dermocosméticos", "vitaminas"],
        },
        {
          name: "Drogaria Popular",
          categorySlug: "farmácias",
          region: "Zona Norte",
          description: "Medicamentos com os melhores preços, genéricos e similares. Atendimento rápido e estoque completo no bairro.",
          address: "Av. Saul Elkind, 890 - Conjunto Parigot de Souza, Londrina",
          phone: "(43) 3399-1122",
          whatsapp: "5543993003300",
          rating: 4.0,
          reviewsCount: 41,
          planType: "free",
          verified: false,
          photoUrl: "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800",
          hours: "Seg-Sáb: 7h–22h | Dom: 9h–18h",
          zone: "norte",
          cnpj: "56.789.432/0001-15",
          ownerName: "Paulo Henrique Lima",
          ownerEmail: "contato@drogariapopular.com.br",
          ownerPhone: "(43) 99300-3300",
          cep: "86082-000",
          street: "Avenida Saul Elkind",
          number: "890",
          neighborhood: "Conjunto Parigot de Souza",
          lat: "-23.2650",
          lng: "-51.1410",
          instagram: "@drogariapopularlondrina",
          paymentMethods: ["Dinheiro", "PIX"],
          tags: ["farmácia", "genéricos", "preço baixo"],
        },
        {
          name: "Padaria Arte do Pão",
          categorySlug: "padarias",
          region: "Zona Leste",
          description: "Pães artesanais, bolos caseiros, salgados frescos e café colonial. Feito com amor toda manhã no Jardim Québec.",
          address: "Rua dos Pioneiros, 560 - Jardim Québec, Londrina",
          phone: "(43) 3366-4400",
          whatsapp: "5543991001100",
          rating: 4.7,
          reviewsCount: 155,
          planType: "destaque",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800",
          hours: "Seg-Dom: 5h30–20h",
          zone: "leste",
          cnpj: "67.890.543/0001-16",
          ownerName: "Dona Tereza Machado",
          ownerEmail: "contato@artedopao.com.br",
          ownerPhone: "(43) 99100-1100",
          cep: "86065-480",
          street: "Rua dos Pioneiros",
          number: "560",
          neighborhood: "Jardim Québec",
          lat: "-23.3210",
          lng: "-51.1430",
          instagram: "@artedopaolondrina",
          paymentMethods: ["Dinheiro", "PIX", "Cartão de débito"],
          tags: ["pão artesanal", "bolo", "salgados", "café colonial"],
        },
        {
          name: "Elétrica Londrina Serviços",
          categorySlug: "servicos",
          region: "Zona Sul",
          description: "Instalações elétricas residenciais e comerciais, manutenção, CFTV e automação residencial. Equipe licenciada e segurada.",
          address: "Rua Professor João Cândido, 210 - Vila Casoni, Londrina",
          phone: "(43) 3377-8899",
          whatsapp: "5543995009900",
          rating: 4.5,
          reviewsCount: 73,
          planType: "free",
          verified: false,
          photoUrl: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800",
          hours: "Seg-Sex: 8h–18h | Sáb: 8h–13h",
          zone: "sul",
          cnpj: "78.901.654/0001-17",
          ownerName: "Roberto Santana",
          ownerEmail: "contato@eletricalondrina.com.br",
          ownerPhone: "(43) 99500-9900",
          cep: "86015-320",
          street: "Rua Professor João Cândido",
          number: "210",
          neighborhood: "Vila Casoni",
          lat: "-23.3110",
          lng: "-51.1540",
          instagram: "@eletricalondrina",
          paymentMethods: ["Dinheiro", "PIX"],
          tags: ["eletricista", "CFTV", "automação", "manutenção elétrica"],
        },
        {
          name: "Clínica Bem Estar",
          categorySlug: "saude",
          region: "Zona Sul",
          description: "Clínica multidisciplinar com psicologia, nutrição, fisioterapia e medicina estética. Cuidado integral para toda a família.",
          address: "Al. Júlio César Gomes da Rocha, 650 - Gleba Palhano, Londrina",
          phone: "(43) 3344-7711",
          whatsapp: "5543994004400",
          rating: 4.8,
          reviewsCount: 188,
          planType: "premium",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800",
          hours: "Seg-Sex: 8h–20h | Sáb: 8h–14h",
          zone: "sul",
          cnpj: "89.012.765/0001-18",
          ownerName: "Dra. Carolina Tavares",
          ownerEmail: "contato@clinicabemestar.com.br",
          ownerPhone: "(43) 99400-4400",
          cep: "86050-200",
          street: "Alameda Júlio César Gomes da Rocha",
          number: "650",
          neighborhood: "Gleba Palhano",
          lat: "-23.3290",
          lng: "-51.1880",
          instagram: "@clinicabemestarlondrina",
          website: "https://clinicabemestar.com.br",
          paymentMethods: ["PIX", "Cartão de crédito", "Cartão de débito"],
          tags: ["psicologia", "nutrição", "fisioterapia", "medicina estética"],
        },
        {
          name: "OdontoLondrina",
          categorySlug: "saude",
          region: "Centro",
          description: "Clínica odontológica completa com implantes, ortodontia, clareamento e próteses. Tecnologia de ponta e equipe especializada.",
          address: "Rua Quintino Bocaiúva, 490 - Centro, Londrina",
          phone: "(43) 3311-9988",
          whatsapp: "5543997007700",
          rating: 4.6,
          reviewsCount: 122,
          planType: "destaque",
          verified: true,
          photoUrl: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800",
          hours: "Seg-Sex: 8h–19h | Sáb: 8h–13h",
          zone: "centro",
          cnpj: "90.123.876/0001-19",
          ownerName: "Dr. André Moura",
          ownerEmail: "contato@odontolondrina.com.br",
          ownerPhone: "(43) 99700-7700",
          cep: "86020-150",
          street: "Rua Quintino Bocaiúva",
          number: "490",
          neighborhood: "Centro",
          lat: "-23.3040",
          lng: "-51.1680",
          instagram: "@odontolondrina",
          website: "https://odontolondrina.com.br",
          paymentMethods: ["PIX", "Cartão de crédito", "Cartão de débito"],
          tags: ["dentista", "implantes", "ortodontia", "clareamento"],
        },
        {
          name: "Auto Mecânica Confiança",
          categorySlug: "servicos",
          region: "Zona Norte",
          description: "Mecânica geral, funilaria, pintura, elétrica automotiva e troca de óleo. 25 anos de experiência em Londrina.",
          address: "Av. Benjamin Constant, 1340 - Conjunto Cafezal, Londrina",
          phone: "(43) 3355-3300",
          whatsapp: "5543998008800",
          rating: 4.3,
          reviewsCount: 58,
          planType: "free",
          verified: false,
          photoUrl: "https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=800",
          hours: "Seg-Sex: 7h30–18h | Sáb: 7h30–13h",
          zone: "norte",
          cnpj: "01.234.987/0001-20",
          ownerName: "Seu Antônio Ferreira",
          ownerEmail: "contato@mecanicaconfianca.com.br",
          ownerPhone: "(43) 99800-8800",
          cep: "86027-700",
          street: "Avenida Benjamin Constant",
          number: "1340",
          neighborhood: "Conjunto Cafezal",
          lat: "-23.2800",
          lng: "-51.1580",
          instagram: "@mecanicaconfianca",
          paymentMethods: ["Dinheiro", "PIX"],
          tags: ["mecânica", "funilaria", "troca de óleo", "elétrica automotiva"],
        },
      ])
      .returning();

    logger.info({ count: businesses.length }, "Businesses seeded");

    const passwordHash = await bcrypt.hash(DEFAULT_PASSWORD, 10);

    const usersData = businesses.map((b) => ({
      businessId: b.id,
      email: b.ownerEmail!,
      passwordHash,
    }));

    await db.insert(businessUsersTable).values(usersData);
    logger.info({ count: usersData.length }, "Business users seeded");

    logger.info("=== LOGINS DOS LOJISTAS ===");
    logger.info("Senha padrão para todos: Hub@2026");
    for (const b of businesses) {
      logger.info(`${b.name} | ${b.ownerEmail} | Hub@2026`);
    }

    const productsData = [
      { businessId: businesses[0].id, name: "Rodízio de Carnes Completo", description: "Rodízio com mais de 15 cortes de carne, buffet de saladas e acompanhamentos", price: "79.90", sortOrder: 0 },
      { businessId: businesses[0].id, name: "Buffet Almoço Executivo", description: "Buffet por quilo com pratos quentes, saladas e sobremesa", price: "49.90", sortOrder: 1 },
      { businessId: businesses[0].id, name: "Porção de Picanha na Brasa", description: "400g de picanha grelhada com farofa e vinagrete", price: "89.90", sortOrder: 2 },

      { businessId: businesses[1].id, name: "Espeto Corrido Premium", description: "Rodízio com 20+ cortes incluindo Wagyu, acompanhamentos e sobremesa", price: "119.90", sortOrder: 0 },
      { businessId: businesses[1].id, name: "Costela no Bafo (1kg)", description: "Costela cozida lentamente por 8 horas com tempero especial", price: "129.90", sortOrder: 1 },

      { businessId: businesses[2].id, name: "Lasanha da Nona", description: "Lasanha artesanal com molho bolonhesa e bechamel", price: "42.90", sortOrder: 0 },
      { businessId: businesses[2].id, name: "Pizza Margherita Napolitana", description: "Massa fermentada 48h, molho San Marzano, mussarela de búfala", price: "54.90", sortOrder: 1 },
      { businessId: businesses[2].id, name: "Ravióli de Ricota com Espinafre", description: "Ravióli artesanal ao molho de tomates frescos", price: "38.90", sortOrder: 2 },

      { businessId: businesses[3].id, name: "Coloração Completa", description: "Coloração profissional com produtos importados, inclui hidratação", price: "180.00", sortOrder: 0 },
      { businessId: businesses[3].id, name: "Corte + Escova", description: "Corte feminino personalizado com escova modeladora", price: "120.00", sortOrder: 1 },
      { businessId: businesses[3].id, name: "Manicure + Pedicure Gel", description: "Nail art em gel com design personalizado", price: "95.00", sortOrder: 2 },

      { businessId: businesses[4].id, name: "Corte Masculino Completo", description: "Corte com máquina e tesoura, inclui barba", price: "45.00", sortOrder: 0 },
      { businessId: businesses[4].id, name: "Escova Progressiva", description: "Alisamento progressivo com produtos profissionais", price: "250.00", sortOrder: 1 },

      { businessId: businesses[5].id, name: "Plano Mensal Premium", description: "Acesso ilimitado: musculação, crossfit, aulas coletivas, vestiário VIP", price: "149.90", sortOrder: 0 },
      { businessId: businesses[5].id, name: "Personal Trainer (10 sessões)", description: "Pacote de 10 sessões individuais com personal trainer", price: "590.00", sortOrder: 1 },

      { businessId: businesses[6].id, name: "Plano Mensal Básico", description: "Musculação e cardio, acesso de segunda a sábado", price: "79.90", sortOrder: 0 },
      { businessId: businesses[6].id, name: "Plano Família (3 pessoas)", description: "3 acessos mensais ilimitados com desconto", price: "199.90", sortOrder: 1 },

      { businessId: businesses[7].id, name: "Cesta Básica Bom Preço", description: "30 itens essenciais selecionados com melhor preço", price: "189.90", sortOrder: 0 },
      { businessId: businesses[7].id, name: "Kit Churrasco (5kg)", description: "Picanha, linguiça, fraldinha, pão de alho e carvão", price: "149.90", sortOrder: 1 },

      { businessId: businesses[9].id, name: "Espresso Duplo Especial", description: "Café de origem única, torrefação artesanal", price: "14.90", sortOrder: 0 },
      { businessId: businesses[9].id, name: "Brunch Completo", description: "Café, suco, pão artesanal, ovos, frutas e granola", price: "49.90", sortOrder: 1 },
      { businessId: businesses[9].id, name: "Bolo de Cenoura com Chocolate", description: "Fatia generosa do bolo artesanal da casa", price: "16.90", sortOrder: 2 },

      { businessId: businesses[10].id, name: "Café Coado Especial", description: "Café de fazenda parceira no norte do Paraná", price: "12.90", sortOrder: 0 },
      { businessId: businesses[10].id, name: "Almoço Executivo", description: "Prato do dia com entrada, principal e sobremesa", price: "39.90", sortOrder: 1 },

      { businessId: businesses[11].id, name: "Banho + Tosa Higiênica (P)", description: "Para cães de pequeno porte até 10kg", price: "65.00", sortOrder: 0 },
      { businessId: businesses[11].id, name: "Banho + Tosa Completa (M)", description: "Para cães de porte médio de 10 a 25kg", price: "95.00", sortOrder: 1 },
      { businessId: businesses[11].id, name: "Ração Premium 15kg", description: "Ração super premium para cães adultos", price: "189.90", sortOrder: 2 },

      { businessId: businesses[12].id, name: "Consulta Veterinária", description: "Consulta completa com exame clínico geral", price: "150.00", sortOrder: 0 },
      { businessId: businesses[12].id, name: "Vacinação V10", description: "Vacina polivalente para cães com certificado", price: "120.00", sortOrder: 1 },

      { businessId: businesses[13].id, name: "Vitamina C 1000mg (60 caps)", description: "Suplemento de vitamina C de alta absorção", price: "39.90", sortOrder: 0 },
      { businessId: businesses[13].id, name: "Protetor Solar FPS 50", description: "Proteção UVA/UVB para uso diário", price: "69.90", sortOrder: 1 },

      { businessId: businesses[15].id, name: "Pão Italiano Artesanal", description: "Pão de fermentação natural, crosta crocante", price: "12.90", sortOrder: 0 },
      { businessId: businesses[15].id, name: "Bolo de Chocolate Belga", description: "Bolo inteiro (1.5kg) com ganache", price: "65.00", sortOrder: 1 },
      { businessId: businesses[15].id, name: "Kit Café Colonial (4 pessoas)", description: "Pães, bolos, frios, geleias e café", price: "89.90", sortOrder: 2 },

      { businessId: businesses[16].id, name: "Instalação Elétrica Residencial", description: "Projeto e execução completa para até 100m²", price: "2500.00", sortOrder: 0 },
      { businessId: businesses[16].id, name: "Instalação de Câmeras CFTV", description: "Kit 4 câmeras HD com instalação e DVR", price: "1800.00", sortOrder: 1 },

      { businessId: businesses[17].id, name: "Consulta Psicologia (50min)", description: "Sessão individual com psicólogo especialista", price: "200.00", sortOrder: 0 },
      { businessId: businesses[17].id, name: "Avaliação Nutricional Completa", description: "Bioimpedância, plano alimentar e retorno", price: "280.00", sortOrder: 1 },

      { businessId: businesses[18].id, name: "Limpeza Dental Completa", description: "Profilaxia com ultrassom e polimento", price: "180.00", sortOrder: 0 },
      { businessId: businesses[18].id, name: "Clareamento a Laser", description: "Clareamento dental a laser em sessão única", price: "890.00", sortOrder: 1 },

      { businessId: businesses[19].id, name: "Troca de Óleo + Filtro", description: "Óleo sintético 5W30 + filtro de óleo + verificação geral", price: "189.90", sortOrder: 0 },
      { businessId: businesses[19].id, name: "Revisão Completa", description: "Freios, suspensão, motor, elétrica e diagnóstico eletrônico", price: "350.00", sortOrder: 1 },
    ];

    await db.insert(productsTable).values(productsData);
    logger.info({ count: productsData.length }, "Products seeded");

    const reviewsData = [
      { businessId: businesses[0].id, author: "Maria Silva", rating: 5, text: "Ótimo ambiente, comida deliciosa e preço justo. Voltarei com certeza!" },
      { businessId: businesses[0].id, author: "João Pereira", rating: 4, text: "Excelente buffet, variedade incrível. O atendimento poderia ser mais rápido." },
      { businessId: businesses[1].id, author: "Ana Costa", rating: 5, text: "A melhor churrascaria de Londrina, sem dúvida. Os cortes são incríveis!" },
      { businessId: businesses[1].id, author: "Carlos Oliveira", rating: 5, text: "Perfeito para comemorar datas especiais. Ambiente sofisticado e carne de primeira." },
      { businessId: businesses[3].id, author: "Fernanda Lima", rating: 5, text: "Profissionais maravilhosos! Saí com o cabelo perfeito. Super recomendo!" },
      { businessId: businesses[3].id, author: "Beatriz Souza", rating: 5, text: "Atendimento impecável, ambiente super clean. Já sou cliente fiel há 2 anos." },
      { businessId: businesses[5].id, author: "Rafael Santos", rating: 5, text: "Academia completa, equipamentos novos e professores dedicados. Melhor da região!" },
      { businessId: businesses[9].id, author: "Larissa Mendes", rating: 5, text: "O melhor café de Londrina. Barista conhece muito e o ambiente é lindo." },
      { businessId: businesses[9].id, author: "Thiago Alves", rating: 5, text: "Venho toda semana para trabalhar. Café incrível e wi-fi perfeito." },
      { businessId: businesses[12].id, author: "Cristina Ferreira", rating: 5, text: "Atendimento veterinário de excelência. Cuida dos meus dois gatinhos com muito carinho." },
    ];

    const reviews = await db.insert(reviewsTable).values(reviewsData).returning();
    logger.info({ count: reviews.length }, "Reviews seeded");

    logger.info("Startup seed completed successfully");
  } catch (err) {
    logger.error({ err }, "Startup seed failed — continuing without seed data");
  }
}
