import {
  pgTable,
  serial,
  integer,
  text,
  real,
  boolean,
  timestamp,
  pgEnum,
  index,
  numeric,
} from "drizzle-orm/pg-core";

export const planTypeEnum = pgEnum("plan_type", [
  "free",
  "destaque",
  "premium",
]);

export const businessesTable = pgTable(
  "businesses",
  {
    id: serial("id").primaryKey(),
    name: text("name").notNull(),
    categorySlug: text("category_slug").notNull(),
    region: text("region").notNull(),
    description: text("description").notNull(),
    address: text("address").notNull(),
    phone: text("phone"),
    whatsapp: text("whatsapp"),
    rating: real("rating").notNull().default(0),
    reviewsCount: integer("reviews_count").notNull().default(0),
    planType: planTypeEnum("plan_type").notNull().default("free"),
    verified: boolean("verified").notNull().default(false),
    photoUrl: text("photo_url"),
    hours: text("hours"),
    clicks: integer("clicks").notNull().default(0),
    whatsappClicks: integer("whatsapp_clicks").notNull().default(0),
    isVisible: boolean("is_visible").notNull().default(true),
    zone: text("zone").notNull().default("centro"),
    cnpj: text("cnpj"),
    ownerName: text("owner_name"),
    ownerEmail: text("owner_email"),
    ownerPhone: text("owner_phone"),
    logoUrl: text("logo_url"),
    bannerUrl: text("banner_url"),
    photos: text("photos").array().default([]),
    cep: text("cep"),
    street: text("street"),
    number: text("number"),
    neighborhood: text("neighborhood"),
    city: text("city").default("Londrina"),
    state: text("state").default("PR"),
    lat: numeric("lat"),
    lng: numeric("lng"),
    instagram: text("instagram"),
    website: text("website"),
    paymentMethods: text("payment_methods").array().default([]),
    tags: text("tags").array().default([]),
    videoUrl: text("video_url"),
    boostedUntil: timestamp("boosted_until"),
    homeFeatured: boolean("home_featured").notNull().default(false),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    index("businesses_category_slug_idx").on(t.categorySlug),
    index("businesses_region_idx").on(t.region),
    index("businesses_rating_idx").on(t.rating),
  ],
);

export type InsertBusiness = typeof businessesTable.$inferInsert;
export type Business = typeof businessesTable.$inferSelect;
